#parameters:
#    flotz_txt_local:
#        username: your@email.com
#        hash: "your hash here"

services:
    flotz_txtlocal:
        class:        Flotz\TxtLocalBundle\Service\TxtLocal
        arguments:    ["@kernel"]
